
TRUE_DIC ={
    0:['true', 'true'],
    1:['true', 'true'],
    2:['true', 'true'],
    3:['true', 'true'],
    4:['false', 'false'],
    5:['true', 'true', 'true', 'true'],
    6:['false', 'false'],
    7:['false'],
    8:['false', 'false'],
    9:['false', 'true', 'true'],
    10:['true', 'true'],
    11:['true', 'true'],
    12:['true', 'true'],
    13:['false', 'true'],
    14:['false', 'true'],
    15:['true', 'true'],
    16:['false', 'false'],
    17:['true', 'false'],
    18:['false', 'true'],
    19:['true', 'true'],
    20:['true', 'true'],
    21:['true', 'true'],
    22:['true', 'true'],
    23:['true', 'true'],
    24:['false', 'true'],
    25:['true', 'true'],
    26:['true', 'true'],
    27:['true', 'false'],
    28:['false', 'false'],
    29:['true', 'true'],
    30:['true', 'false'],
    31:['true', 'false', 'false'],
    32:['false', 'true'],
    33:['false', 'true'],
    34:['false', 'false'],
    35:['false', 'false'],
    36:['false', 'false'],
    37:['false', 'false'],
    38:['false', 'true', 'true'],
    39:['true', 'false'],
    40:['true', 'false'],
    41:['false', 'true'],
    42:['false', 'false'],
    43:['false', 'false'],
    44:['false', 'false'],
}